const GET_PLAYERS = 'GET_PLAYERS';
const UPDATE_PLAYERS = 'UPDATE_PLAYERS';
const REMOVE_PLAYER = 'REMOVE_PLAYER';
const KILL_PLAYER = 'KILL_PLAYER';
const SET_NICKNAME = 'SET_NICKNAME';

module.exports = {
  GET_PLAYERS,
  UPDATE_PLAYERS,
  REMOVE_PLAYER,
  KILL_PLAYER,
  SET_NICKNAME
}
