const UPDATE_BOMB_POSITIONS = 'UPDATE_BOMB_POSITIONS';
const ADD_BOMB = 'ADD_BOMB';
const REMOVE_PLAYER_BOMBS = 'REMOVE_PLAYER_BOMBS';

module.exports = {
  UPDATE_BOMB_POSITIONS,
  ADD_BOMB,
  REMOVE_PLAYER_BOMBS
}
